--- 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redwine
spec:
  replicas: 1
  template: 
    metadata:
      labels: 
        app: redwine
    spec:
      containers:
      - name: redwine
        image: sqlsatbrbiaksacr.azurecr.io/redwine:v1
        ports:
        - containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: redwine
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: redwine